---
- name: Install MySQL server
  yum:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "your_secure_password"
    host_all: true
    state: present
